kaleido-io/terraform-provider-kaleido

examples/multi_region_customize/.gitignore
examples/multi_region_customize/README.md
examples/multi_region_customize/main.tf
examples/multi_region_customize/variables.tf

The `simple_env` sample picks up the deployment zone implicitly from the API URL region that is used for the metadata.
This PR adds a sample that sets the deployment zone explicitly, demonstrating how you could whitelist and deploy to additional regions within a multi-region environment.

Add an example of customizing deployment zones

---

kaleido/common_test.go
kaleido/resource_service.go
kaleido/resource_service_test.go

This feature is based on the Kaleido API schema to return the webui for a new IPFS service

Adding support to allow reading IPFS web UI URL

---

examples/multi_region_with_b2b/main.tf
go.mod
go.sum
kaleido/resource_configuration.go
kaleido/resource_consortium.go
kaleido/resource_environment.go
kaleido/resource_service.go

A few incremental improvements:
- The `shared_deployment` logic should ignore deleted/deleting resources
- The `shared_deployment` logic for services, should only function for `utility` services
- Avoid pass-by-reference of the Terraform `details` object to the REST API layer, as we were picking up generated info
For the last point, it's illustrated with this `terraform plan` output that shows us trying to un-set the `ipfs_peer_id` that Kaleido generated.
```
~ resource "kaleido_service" "ipfs" {
~ details           = {
- "ipfs_peer_id"   = "QmeojRGEwaX9vK3zizHXj2ucUYfVV7bWQ7DVjZCn6VdRim" -> null
}
id                = "zzubxbrt2f"
name              = "sender ipfs"
}
```

Shared tweaks

---

go.mod
go.sum
kaleido/provider.go
kaleido/provider_test.go
kaleido/resource_appcreds.go
kaleido/resource_appcreds_test.go
kaleido/resource_configuration.go
kaleido/resource_configuration_test.go
kaleido/resource_consortium.go
kaleido/resource_consortium_test.go
kaleido/resource_czone.go
kaleido/resource_destination.go
kaleido/resource_environment.go
kaleido/resource_environment_test.go
kaleido/resource_ezone.go
kaleido/resource_invitation.go
kaleido/resource_invitation_test.go
kaleido/resource_membership.go
kaleido/resource_membership_test.go
kaleido/resource_node.go
kaleido/resource_node_test.go
kaleido/resource_privatestack_bridge.go
kaleido/resource_privatestack_bridge_test.go
kaleido/resource_service.go
kaleido/resource_service_test.go
main.go

- Adds a `kaleido_privatestack_bridge` `data` resource for querying the configuration of the privatestack bridge
- Allows an application credential to be mixed into the config by the provider, to provide a fully formed config
- Adds full `urls` Map output to `kaleido_service` and `kaleido_node` resources
- Updates copyright headers
- Depends on https://github.com/kaleido-io/kaleido-sdk-go/pull/36

Updates to headers, data getter for bridge config, and full list of service/node URLs

---

kaleido/resource_environment.go

Hit a bug where the environment would appear like it needed to be changed every `apply`:
```
".terraform/terraform.tfstate" 52L, 1561C                                                                                                                                                     1,1           All
- chain_id           = 1425291069 -> null
id                 = "u0*****"
name               = "Dev - Fabric"
}
```
looking in the `terraform.tfstate`, the recorded value was `null` since it was `Optional` but not `Computed`:
```json
"module": "module.kaleido_fabric",
"mode": "managed",
"type": "kaleido_environment",
"name": "env",
"provider": "module.cue.module.kaleido_fabric.provider[\"registry.terraform.io/kaleido-io/kaleido\"]",
"instances": [
{
"schema_version": 0,
"attributes": { …
```

Recording chain_id on Environment Creation

---

kaleido/resource_configuration.go

- On read for configuration resource only set "details" when "details" field is originally set in module.
- Set details to nil for resource data if details_json is defined in the tf module. 
- Add resource read to return statements for create/ update to update resource data appropriately

Configuration Resource Details update

---

examples/platform_stack/main.tf
examples/platform_stack_multiparty_sandbox/.gitignore
examples/platform_stack_multiparty_sandbox/main.tf
examples/platform_stack_multiparty_sandbox/variables.tf
kaleido/platform/ams_task.go
kaleido/platform/cms_action_create_api.go
kaleido/platform/cms_action_deploy.go
kaleido/platform/cms_build.go
kaleido/platform/common.go
kaleido/platform/environment.go
kaleido/platform/firefly_registration.go
kaleido/platform/firefly_registration_test.go
kaleido/platform/kms_key.go
kaleido/platform/kms_wallet.go
kaleido/platform/mockserver_test.go
kaleido/platform/network.go
kaleido/platform/runtime.go
kaleido/platform/service.go
kaleido/resource_appcreds.go
kaleido/resource_configuration.go
kaleido/resource_consortium.go
kaleido/resource_czone.go
kaleido/resource_destination.go
kaleido/resource_environment.go
kaleido/resource_ezone.go
kaleido/resource_invitation.go
kaleido/resource_membership.go
kaleido/resource_node.go
kaleido/resource_service.go

Work in progress - list will grow:
- Without this a rename of a `kaleido_platform_runtime`, causes the `kaleido_platform_services` to recreate
- Shared blockchain node(s)
- Shared IPFS node(s)
- Shared contract manager, transaction manager, and key manager services/runtimes
- Shared FireFly runtime, but dedicated FireFly service/namespace per member
- Wallet per member (in shared key manager)
- Seed based deployment of batch pin smart contract, using a separate wallet + gateway-mode FireFly
- Asset Manager per member
- `kaleido_platform_firefly_registration`

Avoid setting IDs to unknown in plan for update, and deliver multi-party sample

---

examples/platform_stack/main.tf
kaleido/platform/ams_task.go
kaleido/platform/ams_task_test.go
kaleido/platform/mockserver_test.go

Currently we push everything into the `task_yaml` on a task definition, and let the Kaleido API do the heavy lifting reconciling a new version each time. This is problematic as:
- You can't have a separate `description` for the Task and each Version
- You can't specify an `exampleInput`
Instead this PR changes things so the `name` and `description` move to the top-level task, and the `task_yaml` is just the version part.
You still get the automatic bumping of versions with this.

API change: Split out task version APIs to allow `description` and `exampleInput` on ver

---

examples/platform_stack/main.tf
examples/platform_stack/variables.tf
examples/platform_stack_multiparty_sandbox/main.tf
examples/platform_stack_multiparty_sandbox/variables.tf

Updated terraform examples for both platform_stack and platform_multiparty_stack to support creating both signing and non-signing nodes as well as added in the ability to automatically create an indexer runtime and service

Updated Node Types and indexer in platform_stack and platform_multiparty_stack examples

---

examples/platform_stack/main.tf
examples/platform_stack_multiparty_sandbox/main.tf

removed signer vs non-signer node types for now until EVM gateway updates. This change just simply adds KBI to both the platform_stack and multiparty_platform_stack examples

updated to just be KBI addition

---

examples/platform_stack/main.tf
kaleido/platform/ams_dmlistener.go
kaleido/platform/ams_dmlistener_test.go
kaleido/platform/cms_action_create_api.go
kaleido/platform/cms_action_create_api_test.go
kaleido/platform/common.go
kaleido/platform/mockserver_test.go

Note: unit tests are currently broken as of https://github.com/kaleido-io/terraform-provider-kaleido/pull/65 (and they don't run on PRs or on the branch)

Add type for data model listeners

---

examples/platform_stack_multiparty_sandbox/main.tf
kaleido/platform/cms_action_base_test.go
kaleido/platform/cms_action_deploy.go
kaleido/platform/cms_action_deploy_test.go

Contract manager is now able to deploy directly through transaction manager for cases where a firefly namespace is not available (or not available yet). e.g. when deploying the batch pin contract.  This PR updated the provider to exploit that new ability.

deploy to transaction manager

---

kaleido/platform/ams_dmlistener.go
kaleido/platform/ams_dmupsert.go
kaleido/platform/ams_dmupsert_test.go
kaleido/platform/common.go
kaleido/platform/mockserver_test.go

This isn't quite like the other resources, as it's an update only (no-op read/delete), but it's useful to be able to use declarative syntax to write information about things like deployed smart contracts

Provide utility resource to upsert data model

---

.github/workflows/go.yaml
kaleido/platform/runtime.go
kaleido/platform/runtime_test.go

Allows for leveraging the lower-level features of the platform to customize the scheduling and storage of runtimes, such as Besu and IPFS.

[runtime] Support for storageSize, storageType, zone, and subZone

---

examples/platform_stack/main.tf
examples/platform_stack_multiparty_sandbox/main.tf
examples/platform_stack_two_env_besu_network/main.tf
kaleido/platform/network_test.go
kaleido/platform/stacks_test.go

@chrisbygrave added extra checks today to enforce in service manager adding services of the correct network type within stacks
https://github.com/kaleido-io/firefly-enterprise/pull/3274
Fixing these examples as they will now be caught as errors in dev.
Valid network types can be found here: https://github.com/kaleido-io/firefly-enterprise/blob/main-v3/common/ts-interfaces/src/enums/networks.ts#L1
```
export enum NetworkType {
BESUNETWORK = 'BesuNetwork',
IPFSNETWORK = 'IPFSNetwork',
BITCOINNETWORK = 'BitcoinNetwork',
ETHEREUMPOSNETWORK = 'EthereumPOSNetwork',
}
```

Fix network types in examples

---

kaleido/platform/network.go
kaleido/platform/runtime.go
kaleido/platform/service.go

Exposing the `force` parameter for deleting Kaleido platform services.

add force delete option for platform services, runtimes, and networks

---

kaleido/kaleidobase/providerdata.go

There's ways to eventually set this `Version` via build args so that other info like commit hash, etc. could be included. But this alone will help us to distinguish traffic from our UI vs. Terraform users more easily, and see what versions people are on going forward.

[util] Set User-Agent Header for Diagnostics

---

kaleido/platform/runtime.go
kaleido/platform/service.go
kaleido/platform/stacks.go

Moving Runtimes/ Services between stacks is supported in the Kaleido Platform console

Add requireReplace to the stack id attribute for services and runtimes

---

examples/platform_multiaccountenv_testnets/.gitignore
examples/platform_multiaccountenv_testnets/README.md
examples/platform_multiaccountenv_testnets/input.tfvars.example
examples/platform_multiaccountenv_testnets/main.tf
examples/platform_multiaccountenv_testnets/variables.tf
examples/platform_two_account_besu_network/README.md
examples/platform_two_account_besu_network/main.tf
kaleido/kaleidobase/providerdata.go
kaleido/platform/account.go
kaleido/platform/account_test.go
kaleido/platform/common.go
kaleido/platform/mockserver_test.go
kaleido/platform/network_connector.go
kaleido/platform/network_connector_test.go

`data.kaleido_platform_account` for discovering the account ID of the API key + platform host in-use.
Support for the `type = "Platform"` of network connectors, allowing for requestors and acceptors to peer their disparate networks together if running within the same instance.
Adds connection limits and retry backoff to API calls for when platform 429's are encountered.
`platform_multiaccountenvs_testnets` uses the new `Platform` network connectors to demonstrate how to create a 3 member testnet of Besu and IPFS, with the originator acting as the bridge for the two joiner.

[connectors] [accounts] Data Source for Account ID Info and Platform Connector Support

---

docs/resources/platform_service.md
kaleido/platform/service.go

Some Kaleido service's may take awhile to go into a Ready state (blockchain nodes syncing for example). This allows for configuring that behavior within the provider for service's specifically.

[platform] [service] 'wait_for_ready' Option for Syncing Node Services

---

docs/resources/platform_cms_action_createapi.md
kaleido/platform/cms_action_create_api.go

We've regressed the intended default behavior where if multi-party mode is enabled, and publish is null/undefined, it should be published. So we refactored it to an enum with values `auto` and `never`.

[cms] [createapi] Switching Publish to an Enum
